# Generated by Django 5.2.17 on 2026-08-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='horario',
            name='unique_horario_agenda_data_inicio',
        ),
        migrations.AddField(
            model_name='agenda',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='especialista',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name='especialista',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('email',), name='unique_active_especialista_email'),
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('agenda', 'data', 'hora_inicio'), name='unique_active_horario_agenda_data_inicio'),
        ),
    ]
